// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/10/2025, 11.39.21
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/User/OneDrive/桌面/New portfolio/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/composables/**/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/utils/**/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/stores/**/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/composables/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/utils/**/*.{js,ts,mjs}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/User/OneDrive/桌面/New portfolio/portfolio/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;