// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 07/12/2025, 4:10:54 pm
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["C:/Users/admin/Desktop/Intern/Portfolio-Site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Desktop/Intern/Portfolio-Site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Desktop/Intern/Portfolio-Site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Desktop/Intern/Portfolio-Site/plugins/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/composables/**/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/utils/**/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/stores/**/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/composables/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/utils/**/*.{js,ts,mjs}","C:/Users/admin/Desktop/Intern/Portfolio-Site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Desktop/Intern/Portfolio-Site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/admin/Desktop/Intern/Portfolio-Site/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;